#!/usr/bin/zsh -
PATH="/usr/bin:$PATH"
wrap_output=""

for ((i = 1; i <= $#; i++)); do
    a="$argv[i]"
    b="$argv[i + 1]"
    if [ -z "$a" ]; then
        argv[i]=()
        ((i--))
    elif [ "$a" = 'rev-parse' ]; then
        wrap_output=yes
    elif [ "$a" = 'worktree' -a "$b" = 'list' ]; then
        wrap_output=yes
    elif [[ "$a" = *longpaths* ]]; then
		# git in cygwin not support core.longpaths
        argv[i]="gc.autodetach=false"
    elif [ "$a[1]" != '-' ]; then 
        argv[i]=`cygpath -u "$a"`
    fi
done

if [ $wrap_output ]; then
    if a=`git "$@"`; then
        if [ -z "$a" ]; then
        elif [[ "$a[1]" = '/' || "$a" = 'worktree '* ]]; then
            echo $a | while read a
            do
                if [ "$a[1]" = '/' ]; then
                    cygpath -w "$a" | sed 's#\\#/#g'
                elif [[ "$a" = 'worktree /'* ]]; then
                    a=${a//worktree /}
                    a=`cygpath -w "$a" | sed 's#\\\\#/#g'`
                    echo "worktree $a"
                else
                    echo "$a"
                fi
            done
        else
            echo $a
        fi
    else
        x=$?
        echo $a
        exit $x
    fi
else
    exec git "$@"
fi
